### ISSUE TITLE
Reducing Nano Denominations and only use NANO

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#100]
Nault is using NANO, knano and nano.

![image](https://user-images.githubusercontent.com/2406720/88685369-2afd5880-d0f6-11ea-80df-faa848eb1df4.png)

Does anyone EVER use anything other than NANO? I think it may just be confusing and dangerous but some users still want it for a nostalgic purpose I don't know. I don't think any other wallet has this feature. This is an old reference to the original raiblock system where Mray (NANO=1M nano) was chosen as the default denomination when exchanges started to list it.

The suggestion is to remove them and only keep NANO.
Related: #93

**Comment by sebrock** [comment]
Reduces complexity.
Removes clutter from the configure-app-setting component.
Easier to configure multi-currency.
We are also not caring for Banoshi at this point in time #93

**Comment by My1** [comment]
I at least use small nano, for me the small numbers I have look a little nicer and stuff
