### ISSUE TITLE
Which additional languages can be covered by translators available to the @Nault/nano team?

### ISSUE THREAD

**Issue by sebrock** [Nault/Nault#101]
Which additional languages can be covered by translators available to ths @Nault/nano team?

_Originally posted by @sebrock in https://github.com/Nault/Nault/issues/83#issuecomment-664984325_

**Comment by BitDesert** [comment]
For me it's german.
We can ask at the Nano and TNC Discord for translators.

**Comment by sebrock** [comment]
> For me it's german.
> We can ask at the Nano and TNC Discord for translators.

German is already on the list. 
I have translators for of the listed languages setup in POE and standing by to work.
I am gonna add you for German though as a second pair of eyes/proofreader. (please end me an email add to send the invite to.
Obviously #83 and #85 must be completed before #84 can be picked up again for completion. 

The question now really is if we badly need any specific  additional language(s) or if there are translators available for an additional language. 
Additional ones can always be handled in a future release.
From 1 available language to 18 that cover 20 locales isn´t too bad of an increase right?

**Comment by Joohansson** [comment]
I can do Swedish but I see very little demand for it as English is pretty much native language here for anyone using a crypto wallet.

**Comment by sebrock** [comment]
> I can do Swedish but I see very little demand for it as English is pretty much native language here for anyone using a crypto wallet.

The more the merrier imho. 
I am going to suggest a phased approach anyways. 
I´ll put Swedish to the last phase then,
@Joohansson To which email address can I send the POEditor invitation?
Best if you DM it to me in Discord.

Adding Swedish to #83
