### ISSUE TITLE
Development Guide

### ISSUE THREAD

**Issue by sebrock** [Nault/Nault#104]
#### Clone repository and install dependencies
```bash
git clone https://github.com/Nault/Nault
cd Nault
npm install
```

#### Run the wallet in dev mode
```bash
npm run wallet:dev
```

If you want to debug in VS code, first install [debugger for chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)
Then you can just go to the debug screen and choose "Launch Chrome http"

#### Run the wallet in dev mode as https (for example if using the Ledger device)
```bash
npm run wallet:dev-ssl
```

To debug in VS code: Go to debug screen and choose "Launch Chrome https"

## Build Wallet (For Production)
Build a production version of the wallet for web:
```bash
npm run wallet:build
```

Build a production version of the wallet for desktop: *(Required for all desktop builds)*
```bash
npm run wallet:build-desktop
```

**Comment by BitDesert** [comment]
Available at https://github.com/Nault/Nault/blob/master/DEVELOPMENT.md
