### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by BitDesert** [Nault/Nault#105]
It would be great to have a common linter which would run for every commit/PR.
That way the codestyle is defined in some config files and everyone could write code that has the same style as from everybody else.

- [x] Define which linter to use
- [x] Initial linting + fixes
- [x] Implement action for every push + PR

**Comment by sebrock** [comment]
Angular´s built-in **ng lint** uses **tslint**
https://github.com/Nault/Nault/blob/d7d9a46dbdbcdd9212b4e1338182ba959a33ba3f/package.json#L87
**tslint has been deprecated**, replacement:[ typescript-eslint](https://eslint.org/) [github](https://github.com/typescript-eslint/typescript-eslint#typescript-eslint)
And there is [angular-eslint](https://github.com/angular-eslint/angular-eslint)

**Comment by sebrock** [comment]
For less, there is [lesslint](https://github.com/lesshint/lesshint)

**Comment by Joohansson** [comment]
Ok working on the initial linting + fix part
