### ISSUE TITLE
Help with NanoVault please!

### ISSUE THREAD

**Issue by SBD-BFR** [Nault/Nault#108]
Dear friend,
I bought some Nano tokens a year ago and stored them in a Ledger Nano S with the NanoVault web app via Brave Browser (it worked fine).
A couple days ago I was checking all my tokens in the Ledger device and it was all good except from Nano...
At first, I tried the same way (web app in Brave) and it could not even connect/read the ledger... same history with Chrome...
Then I downloaded the NanoVault app in a laptop and the first step worked fine, the ledger was connected but it appears that 'Can Not Connect to the Node'... my account have no tokens and keep getting the same message: "Unable to connect to the Nano node, your balances may be inaccurate".
I tried hiding and re creating an account but keep getting the same result.
I´m sure my tokens are somewhere and this has to do with some update or something.
I really hope you can help me with this one.
Big hug from Peru,

**Comment by aleksre** [comment]
NanoVault is not working anymore. Use www.nault.cc instead. It can access your funds on the ledger.

**Comment by BitDesert** [comment]
Or download the desktop app: https://github.com/Nault/Nault/releases/latest

**Comment by SBD-BFR** [comment]
Thank you!
