### ISSUE TITLE
Remove bootstrap dependency

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#109]
https://github.com/Nault/Nault/blob/bb59e4283aaf147e1dfe08a370ce78605d588a8f/src/index.html#L22

overrides certain fonts and applies global styles that add/remove spacing in random unexpected places, alter text colors etc.

it's currently used to create a scan QR modal:
Accounts -> any account -> Enable Remote Signing (checkmark) -> Create New Block -> Scan from QR code

copy the bare minimum styles needed for the modal (overlay+window) so there is no need for the huge css (Nault already uses UIkit)

**Comment by BitDesert** [comment]
I think that's pretty important as it could cause more issues.

**Comment by Joohansson** [comment]
Fixed in #119
