### ISSUE TITLE
Manage known reps only show NF reps

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#11]
Maybe show the suggested list of reps instead?

**Comment by NiFNi** [comment]
I think the handling of representatives should be changed up a bit more. The current way is not really helpful for people not into Nano and representatives already. I can definetely think of some integration of mynano.ninja. Though it might be better to just link there and be not dependent on its API.
My "dream" would be that Nault does not have a rep list at all. Instead it notifies you if your rep might not be the best rep right now using something like these statisitcs:
- Voting weight >2%
- Node is down according to mynano.ninja or maybe even use the node rpc call for representatives: https://docs.nano.org/commands/rpc-protocol/#representatives_online
- blockcount is way behind 
- ...to be extended..

Then have the possibilty to link to Nault with a Rep address as parameter which lets you link from other services like mynano.ninja to directly change your rep in Nault. When clicking this link you can choose between your accounts for which you want to set the rep. And also you can choose to use this rep as a default for future new accounts.

**Comment by Joohansson** [comment]
This also affects the "Default rep" that you can choose in the app settings. Right now only display NF reps.

**Comment by BitDesert** [comment]
Maybe I can port the representative selection from NinjaVault which pulls all available reps and shows them in the list with autocomplete:
https://vault.mynano.ninja/representatives
![grafik](https://user-images.githubusercontent.com/11021604/86532840-2f569d00-becd-11ea-8329-6561b8c6e676.png)
![grafik](https://user-images.githubusercontent.com/11021604/86532831-2239ae00-becd-11ea-9a61-90087c9298d4.png)

**Comment by qwahzi** [comment]
Chiming in that I'd like to see the autofill for "New Representative" default to the MyNanoNinja recommendation list instead of Nano Foundation:

![image](https://user-images.githubusercontent.com/3682613/88087006-da15bf00-cb4d-11ea-8c07-120e43181664.png)

**Comment by BitDesert** [comment]
Added the functionality at #67 .
