### ISSUE TITLE
Bug: Account does not update after importing a new wallet

### ISSUE THREAD

**Issue by aleksre** [Nault/Nault#112]
Steps to reproduce:

1. Import a wallet
2. Select an account in the nav
3. Import another wallet (I imported from a ledger but don't think it matters)

**Expected:** Total balance should be selected in the nav (or an account from my newly imported wallet)
**Actual:** The old account is still selected and shown

Both the account and the rep shown here is from the first wallet, after importing from the ledger.
![image](https://user-images.githubusercontent.com/1097444/88982485-ae6ea380-d2c8-11ea-897d-ff8197384f83.png)

The dropdown shows both my Primary Account (old wallet) and Account#0 (new wallet).
![image](https://user-images.githubusercontent.com/1097444/88982617-14f3c180-d2c9-11ea-8e67-383ff4fda62d.png)

**Comment by Joohansson** [comment]
Solved with commit 0d6e609 and 4e88ca3 which is part of #125
