### ISSUE TITLE
Improved workflow for switching out a bad rep

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#14]
Now you get a warning and has to click on that, then select the right account and a rep from a list. It's many steps for the normal user. I'm thinking if it can be done more semi-automatic with the wallet taking the action and user just approve. I think that will help with weight distribution.

For example a dialog popping up:

> Your account’s representative is not optimal due to high weight. Press OK if you allow Nault to change it for you to rep XYZ. Press MANUAL if you want to select the rep yourself. Or CANCEL if you want to keep a bad rep.

**Comment by aleksre** [comment]
I agree. I think the main issue is there is a lack of motivation for users to change, so it need to be super simple. I imagine a panel above the main content that is displayed automatically and stays untill you change or dismiss it. I would also like those buttons to be more descriptive such as:
- Pick one for me
- Choose from a list of recommended reps
- Keep my current rep

Happy to contribute on this btw

**Comment by BitDesert** [comment]
I'll implement a more comprehensive API service for My Nano Ninja which we can use to improve the flow @aleksre 👌

**Comment by Joohansson** [comment]
I've seen it recommends to switch rep sometimes randomly even if the rep is good. I think mynano indicate it being offline while it's not. That's not very user friendly. Maybe save it as a state and only give notice to the user if it happens two times with 24h apart or something.

**Comment by BitDesert** [comment]
Implemented a rep suggestion at #67 
![grafik](https://user-images.githubusercontent.com/11021604/88159739-03961f80-cc0e-11ea-80bd-ab68026f2a95.png)
