### ISSUE TITLE
Add support for SOCKS5 proxy

### ISSUE THREAD

**Issue by HostFat** [Nault/Nault#149]
Can you add the support for SOCKS5 proxy?

The main goal is being able to set Tor as proxy, so that it is possible to protect the IP of the user while he (through Nault) uses external services/nodes.

**Comment by BitDesert** [comment]
What exactly is the issue? The connection to the backend node?

**Comment by HostFat** [comment]
It is to avoid any direct connection (so, by exposing the IP) with outside services.
So any requests for addresses balance or sending tx to external nodes will be through the Tor network.

By adding the support of SOCKS v5, then users will just need to run Tor in the backround and set: 127.0.0.1:9150 on the SOCKS setting on Nault.

**Comment by BitDesert** [comment]
This is probably only relevant for the desktop app right?

**Comment by HostFat** [comment]
Yes. Only the desktop app.

**Comment by BitDesert** [comment]
This should probably be done on OS level rather than in the app itself.
