### ISSUE TITLE
Current rep in the sidebar not updated when importing Ledger wallet

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#150]
If having another account in Nault and adding a Ledger, the rep stays for the old wallet until you click on it which takes you to the rep page and refreshes. Not sure exactly where this fault is. Probably some "isLedger" variable that has been missed.

**Comment by keerifox** [comment]
i'm guessing RepresentativeService.getRepresentativesOverview() is not being called when the wallet changes. just tested creating a new wallet and it kept displaying previous wallet's rep. doesn't require a ledger on either of the wallets

**Comment by keerifox** [comment]
was mentioned in #112 btw

    Both the account and the rep shown here is from the first wallet

**Comment by Joohansson** [comment]
It's a tricky one. From what I can see the representatives to show comes from here
![image](https://user-images.githubusercontent.com/2406720/89982302-c3a6e300-dc75-11ea-91bc-6cb36bda2807.png)

Which is taken from here:
![image](https://user-images.githubusercontent.com/2406720/89982344-d7524980-dc75-11ea-9460-83f912436d87.png)

But the account list IS reset when the wallet is reset:
![image](https://user-images.githubusercontent.com/2406720/89982397-f18c2780-dc75-11ea-8a47-04a0ff903e69.png)

And that IS called when a seed or ledger is imported:
![image](https://user-images.githubusercontent.com/2406720/89982611-5c3d6300-dc76-11ea-9625-926c94c92634.png)

**Comment by Joohansson** [comment]
Ok now I know (I think). The ngOnInit() in the change-rep-widget.component is only called when you refresh Nault. Not when importing a new wallet, so it never gets updated. Need to find a way to do that.
![image](https://user-images.githubusercontent.com/2406720/89982945-f1d8f280-dc76-11ea-8b57-ff06473d2d41.png)
