### ISSUE TITLE
Request for multiple wallet support

### ISSUE THREAD

**Issue by Compunologist** [Nault/Nault#17]
Nault allows for creating multiple accounts within a wallet. Multiple wallets however are not yet supported. Only one wallet can be active at a time.

Furthermore when importing a wallet, the following message is displayed:

![Importing existing wallet](https://user-images.githubusercontent.com/20874837/86102195-7c94d200-babb-11ea-81f9-b89fb47432d7.JPG)

Of course, the existing wallet and accounts are safe (assuming one has saved the corresponding seed) but as only one wallet can be active at a time the current wallet is overwritten as mentioned by the next message:

![Overwrite your existing wallet message](https://user-images.githubusercontent.com/20874837/86102489-df866900-babb-11ea-844f-6d384720a5b9.JPG)

This may seem to contradict the sentence "none of your existing wallets or accounts are affected" from the previous message.

(Nault v1.3.0, desktop Windows)

**Comment by Joohansson** [comment]
We can alter the text but I think support for multiple wallets is highly unlikely to be implemented. It doesn't make much sense to me why you would want that. It's easy enough to switch wallet by entering a new seed or by importing from a file.

**Comment by Compunologist** [comment]
It is just a matter of convenience. Entering a new seed is still more "work" than selecting a different wallet from a menu. Additionally, if one wants to e.g. transfer funds from a hardware wallet to his/her software wallet, it is nice to have the concerning accounts visible in the same application.
