### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by NiFNi** [Nault/Nault#18]
I think it would be great to have support for multiple languages. It lowers the barrier to join the Nano world for non fluent english speakers.

Angular ships with i18n support. More information can be found here: https://angular.io/guide/i18n

If noone started on this already I think I will probably sooner or later start working on this.

**Comment by BitDesert** [comment]
That would be great!
Is that compatible with Angular 5 and 9? Otherwise we might update the core first with #21

**Comment by NiFNi** [comment]
Yeah I'll definitely wait for #21 to be done before starting this.

**Comment by natastro** [comment]
Hello! I'd be happy to help with Spanish translations if needed. Have a good one!

**Comment by BitDesert** [comment]
@NiFNi We updated to Angular 9 so we're ready to go here!

**Comment by NiFNi** [comment]
@BitDesert yep seen that. Already started having a closer look at it.

**Comment by BitDesert** [comment]
Closed via #457
