### ISSUE TITLE
Export wallet: Include list of indexes instead of the latest index

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#184]
The problem now is if you are using indexes 0,1,2 and 6 the last index is 6 and the next time you load the wallet it will be all 0-6. Better to include a list of indexes. The same problem if you add a custom index of 1000, that will not even be part of the import.

https://github.com/Nault/Nault/blob/master/src/app/services/wallet.service.ts#L329

**Comment by keerifox** [comment]
implemented in #200
