### ISSUE TITLE
Display bug: small info windows visible throughout Nault 

### ISSUE THREAD

**Issue by Compunologist** [Nault/Nault#19]
Each time after using Nault for a few minutes, small info windows stay incorrectly visible in other parts of the Nault application as illustrated by the red arrows in the following screenshot:

![old info windows visible](https://user-images.githubusercontent.com/20874837/86107735-840ba980-bac2-11ea-8167-cfa1a1c90b42.jpg)

(Nault v1.3.0, desktop Windows)

**Comment by Joohansson** [comment]
I can't replicate this, not even with 1.3.0 windows. How did you do it @Compunologist?

**Comment by Compunologist** [comment]
I encountered the issue on 2 laptops, both running Windows 10 but only after using Nault v1.3.0 for a few minutes. Nault is the only program on these laptops which showed this sort of display behavior. Yesterday I installed Nault v1.5.0 on both laptops and so far I have not been able to reproduce the issue, even after having Nault opened and used for 20 minutes.

**Comment by Joohansson** [comment]
Is anyone able to replicate this? Or I will close this issue.
