### ISSUE TITLE
Send page tab for sending between own accounts

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#191]
![image](https://user-images.githubusercontent.com/29272208/91168851-d97cc500-e6c5-11ea-9f5c-5149a8e2b1cf.png)

no need to duplicate layout/code for this, simply switch between text field and dropdown based on which tab it is

**Comment by Joohansson** [comment]
Sounds good to me

**Comment by aleksre** [comment]
Suggest calling this a transfer, rather than send.
