### ISSUE TITLE
Restrict amount text field input to digits and one period

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#192]
![image](https://user-images.githubusercontent.com/29272208/91169250-86574200-e6c6-11ea-9e25-65b1b7ae2219.png)

**Comment by Joohansson** [comment]
And actual valid nano amount, like no less than 1 raw. Suggested to use the full function made for this
https://github.com/Nault/Nault/blob/b2fc145c61f4382822ddbf0a2a05c56b6d08d37a/src/app/services/util.service.ts#L286
or
https://github.com/Nault/Nault/blob/b2fc145c61f4382822ddbf0a2a05c56b6d08d37a/src/app/services/util.service.ts#L300
