### ISSUE TITLE
WHY is any given rep bad?

### ISSUE THREAD

**Issue by My1** [Nault/Nault#199]
the message regarding bad reps is generally a good thing. however there have been multiple instances where the display might have been bugged and it's a very big scare to be honest and it has already been discussed that users changing their reps all over the place is generally not the greatest idea.

so when a bad rep display happens it might be quite useful to display also WHY, which at least hasnt been the case last time I saw it happen to me (yesterday on nano_1fuckbtc...).

also considering these bugs can happen it might be good to (unless it's about an overly large representation, which can be proved easily and without doubt) maybe a review process for this might be needed and until then only a lesser level of caution or whatever

**Comment by keerifox** [comment]
> hasnt been the case last time I saw it happen to me

MyNanoNinja returned a 0% weekly uptime for an online rep

#197 includes some permanent as well as temporary fixes, but it's up to MNN to resolve monitoring issues

**Comment by My1** [comment]
well yeah, but maybe there should be something in between "bad" and "good" like that unless a rep is having way too high with their weight already, I think they shouldnt be marked as bad for an uptime by a service which offers probably no guarantees of any sort, just warn and have a public place where the reps can be then be marked as that they have been checked to have a bad uptime, to not break UX too much.

sure it's extra manual work, but the UX just SUX.

also the message doesnt even state WHY the rep is marked as bad:
![image](https://user-images.githubusercontent.com/6696524/91552370-fadeea80-e92b-11ea-921d-2a277137e1e0.png)
also the current data of MNN doesnt show any problems.
![image](https://user-images.githubusercontent.com/6696524/91552463-22ce4e00-e92c-11ea-98ae-f434333f9798.png)

**Comment by keerifox** [comment]
> also the current data of MNN doesnt show any problems

![image](https://user-images.githubusercontent.com/29272208/91563193-fca9ad80-e92d-11ea-9c22-a4ef3d553cc3.png)

> the message doesnt even state WHY the rep is marked as bad

update to v1.7.7

**Comment by My1** [comment]
okay,. well okay, just rotated through a few bad ones.

maybe the "marked as avoid" part could get an explanation for it, as in why it was marked that way, but looks a lot better than before,

regarding your shot, oops I guess the nault window covered that, lol
