### ISSUE TITLE
Simple privacy implementation

### ISSUE THREAD

**Issue by MikeRow** [Nault/Nault#210]
Dynamic account management and more privacy:

- Receiving account is different everytime the n-1 account received funds
- When sending, it calculates the delta between sending amount and every accounts's balance. The account with lower delta will send the funds. If no accounts have enough balance, the less number of account with enough balance will send funds to account n+1, then it will send the funds to destination

This implementation will change the receiving account everytime to hide to a sender your real balance. (Like it happen on a lot of Bitcoin wallets), giving more privacy to the receiver.

**Comment by Joohansson** [comment]
The idea is not bad but much of how the wallet behaves today would have to change. Like have the wallet scan for rep status of each account, certain lists of all your accounts (dropdowns throughout the wallet) would not make sense anymore, the accounts page would not make sense with thousands of accounts, the wallet export file contains all indexes today, the wallet import would take forever scanning for individual amounts, etc. The whole wallet would more or less have to be redesigned. I don't see this being implemented in a long time. Probably best to offer that in a completely separate wallet project.
