### ISSUE TITLE
Linux Desktop does not produce correct address when importing BIP39

### ISSUE THREAD

**Issue by a-e-johnson** [Nault/Nault#211]
Nault 1.7.9 can import BIP39-mnemonic phrases.
But the desktop-version (linux) does not produce the correct addresses. The web-version works fine.

Nano-tools, nault web-version, magnum wallet all produce the same addresses for a BIP39-mnemonic.
Only the desktop-version of Nault produces different addresses.

I think that may be a bug

**Comment by Joohansson** [comment]
Thanks!
Solved in https://github.com/Nault/Nault/commit/4122424ba457562608e38487f94a526ae51ec0fb
