### ISSUE TITLE
Reconnect Ledger X when using bluetooth on browser refresh

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#222]
Ledger X has been confirmed working using bluetooth and windows 10, using nault.cc.
But when refreshing the browser, the ledger does not connect using BT (I guess it defaults to webHID). The wallet has to be imported again.

 @aleksre An easy fix?

The following tip was made: Make sure the ledger's BT is on and the nano applet runs BEFORE opening nault

**Comment by My1** [comment]
maybe what could also be done could be that the reconnect link spawns a list of options, with Bluetooth and a few USB options from the most recommended one to the least one as no idea how many USB transfer protos it can run, or like Bluetooth, USB, Advanced, where the last one lets you pick more explicitly

**Comment by aleksre** [comment]
Easy fix would be to provide two links for reconnecting the Ledger. One for USB and one for Bluetooth (if supported). 

It would be even better if we could detect which transport was used last time, but I'm not sure if there's a reliable way. Local storage maybe?

**Comment by My1** [comment]
yeah local storage and keeping track of the last one is likely the easiest Idea.

**Comment by Joohansson** [comment]
Why not try both and use the first one that works?

**Comment by My1** [comment]
> Why not try both and use the first one that works?

problem is that trying isnt an automatic process (u2f on anything that isnt windows 10 or Android is, sure but WebUSB, WebHID and WebBT all require the user to select a device to use) which might be weird to the user
