### ISSUE TITLE
Unable to Connect Nault Desktop App to Ledger Nano X

### ISSUE THREAD

**Issue by pjhillig** [Nault/Nault#229]
Hi, I am trying to connect my Ledger Nano X hardware wallet to the Nault application I installed on my computer.  The Ledger is connected via USB to my computer, I have the Nano application open, and I have closed it and reopened it.  Still says "Ledger Device Not Connected."  Please advise.

**Comment by Joohansson** [comment]
We will be looking into this. Seems to only happen with Nano X and not Nano S.

**Comment by pjhillig** [comment]
Ok good. Thank you. Please let me know once it's been resolved.

**Comment by Joohansson** [comment]
@pjhillig I have done a lot of troubleshooting on my new Ledger X now and for me, it was a bad USB port. Using a USB3 port that was in good shape (cable firmly connected in the hole) and a good (short) USB-C cable worked flawlessly for me in the desktop app and browsers. The USB2 port I was testing with only worked in the desktop app and firefox, not in chrome (which gave random errors). The desktop app (and firefox) uses an older type of Ledger protocol and is usually more stable as well (but with an annoying popup in firefox).

Trying different ports and cables is also recommended by Ledger. https://youtu.be/Ob2v02uDCuM

When you switch cable/port you need to also reload Nault. Maybe better to close and open the browser, or close and open the Nault app. Possibly even re-import the Ledger by first resetting the Nault wallet store or create a new temp wallet in between. Does this solve it for you?

I also find my bad USB port works perfectly when the Ledger X was fully charged, not sure yet if that's related or not.

**Comment by pjhillig** [comment]
Actually, I waited a couple days and logged back into my Ledger Viewer application. There were a few updates available, including one for Nano, so I updated my wallet. Then I was able to connect my Ledger Nano X to the Nault application. It is now working for me. 👍🏻 Thank you.
