### ISSUE TITLE
Ledger Nano S/X - Which connection type is supported?

### ISSUE THREAD

**Issue by BitDesert** [Nault/Nault#231]
When configuring a new wallet with a Ledger device it tells you to "click one of the two buttons" and connect via Bluetooth even if your browser/app doesn't support Bluetooth.

Maybe we could tell the user which options are available, maybe with labels:
![grafik](https://user-images.githubusercontent.com/11021604/102823593-754fe080-43db-11eb-8092-e4aeba0bc345.png)

We already have the information on which options are available `ledgerService.supportsBluetooth`:
https://github.com/Nault/Nault/blob/138c7ccfa286ebd6f310990a7a6578994591a5a6/src/app/components/configure-wallet/configure-wallet.component.html#L174

**Comment by My1** [comment]
interesting idea although question is how reliable that is for example on android, for my experience anyway you can scrap BT currently due to some GATT chaos (see #223)

**Comment by aleksre** [comment]
Yeah, we don't really have a way of detecting if BT is actually going to work or not. Currently the button is displayed if your device has any BT support at all, and that essentially means that you can give it a try.

But I'd certainly be in favor of having the description match the buttons. So a description for USB only, and another when both buttons are shown.
