### ISSUE TITLE
Add support for tokens

### ISSUE THREAD

**Issue by HostFat** [Nault/Nault#235]
https://www.reddit.com/r/nanocurrency/comments/klqyyk/a_token_system_for_nano/

https://www.reddit.com/r/nanocurrency/comments/kmxtjt/you_can_now_create_tokens_on_nano_thanks_to

https://github.com/hectorchu/nano-token-cli

https://github.com/hectorchu/gonano-gui

**Comment by qwahzi** [comment]
As a counterpoint, it's risky to add support for this functionality if the Nano protocol will likely change and break this implementation. See some of Colin's concerns here:

![image](https://user-images.githubusercontent.com/3682613/103369280-59a9a180-4a8f-11eb-878d-b9a450ab7374.png)

**Comment by My1** [comment]
I am also not too much in favor of this. Interesting idea sure, but I honestly prefer nano's concept of just being simple and NOT having a ton of L2 stuff or other weird additions
