### ISSUE TITLE
Unable to change representatives for unopened accounts (offline representatives)

### ISSUE THREAD

**Issue by ghost** [Nault/Nault#237]
I had created a nano account 2 years back using NanoVault 

Its representative is offline (I assume the delegated representative was NanoVault earlier).

On nano crawler it says "Unopened account" 
On Nault.cc, when I try to update the representative, it says "None of the accounts selected need to be updated".

Can you have look into this, am I missing something?
I'm able to update the representatives for other accounts whose representatives were NOT nanoVault.

**Comment by keerifox** [comment]
representative cannot be set on an account that has never received any funds, i suppose the error message could be adjusted to make that more clear

**Comment by ghost** [comment]
Okay, I was able to update the representative after sending some funds to it. Thanks!

And yes, maybe the error message could be articulated better for unopened accounts.
