### ISSUE TITLE
Account index is not shown on named accounts

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#241]
currently there's no way to see the account index (which you may need to add the account directly) without temporarily removing the label

![image](https://user-images.githubusercontent.com/29272208/103560694-16e13280-4eb0-11eb-859b-5f5a80dcef17.png)

imo it should display "Account #X" in smaller color-less font above or underneath the address book name

at least on the account details page. it can be avoided in the list of accounts

**Comment by Joohansson** [comment]
Agree
