### ISSUE TITLE
Identicons

### ISSUE THREAD

**Issue by ghost** [Nault/Nault#25]
A few services have added these Natricon cartoon characters that have divided the Nano community. Please don't add them, but add nice looking identicons instead.

**Comment by BitDesert** [comment]
This is highly controversial, but Nault is meant to be a playground to test several things.
Maybe we could built a dropdown setting where you could choose which image you want to show up.
We have several others that looks pretty nice.

**Comment by ghost** [comment]
@BitDesert yeah, there are so many nice identicons out there, like the Stellar ones.
