### ISSUE TITLE
Importing an account loses my old one

### ISSUE THREAD

**Issue by fairking** [Nault/Nault#251]
I don't understand I imported one account and after I imported the second one the first one is gone.
This is very disappointed.

**Comment by keerifox** [comment]
did you import a _wallet_? there is a warning when importing a wallet that your existing wallet will be overwritten

**Comment by fairking** [comment]
Yes, it was a wallet. I found it is only a way to import another account.

**Comment by BitDesert** [comment]
There are two huge warnings when you import a wallet with another one already configured:
![Screenshot_20210110-232145_Firefox.jpg](https://user-images.githubusercontent.com/11021604/104137109-d2b3cd80-539a-11eb-8429-bf50bdab4bfa.jpg)
![Screenshot_20210110-232225_Firefox.jpg](https://user-images.githubusercontent.com/11021604/104137113-d6475480-539a-11eb-86b7-45552a7813e8.jpg)

If you want two wallets at the same time use different browser profiles or a different browser.

**Comment by fairking** [comment]
Ok. Thanks. I was actually using an app.
