### ISSUE TITLE
Add Private Key as import option

### ISSUE THREAD

**Issue by pauloduartedf** [Nault/Nault#26]
We have some wallets that work with private keys, like Exodus, I think it's important to have this option, both on the web wallet and on the desktop. NanoVault implemented it in its web version.

**Comment by BitDesert** [comment]
You can actually import private keys now thanks to the PR #15 by @PlasmaPower 
Head over to https://nault.cc/configure-wallet and choose "Private Key" in the Dropdown:
https://i.imgur.com/eXgXDXt.png
