### ISSUE TITLE
Allow local PoW to be cancelled by the user if it takes too long

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#277]
* CPU pow should be possible by using worker.terminate() on the worker list
* GPU pow: Use the progressCallback to abort https://github.com/numtel/nano-webgl-pow

**Comment by keerifox** [comment]
could display a notification in the sidebar, warning style (orange)

Proof of Work is taking a while...
[Adjust PoW settings]() and/or [cancel]()
