### ISSUE TITLE
Add possibility to send all funds from a wallet

### ISSUE THREAD

**Issue by MikeRow** [Nault/Nault#29]
Add possibility to send all funds from a wallet, so you don't have to send manually from every account

**Comment by Joohansson** [comment]
Interesting idea! So like empty a wallet. Only problem I see with that is if the user has not added all accounts containing funds and thinking they have emptied the wallet when they have not. There are billions of accounts in a seed, can't check for funds in all of them.

**Comment by MikeRow** [comment]
Perhaps an automatic account search could discover accounts with funds on them. 
Taking (again) Electrum as example, Nault could look up to 10 next accounts, of the same seed.
Just looking, but not generating in the wallet, and notifies the user if there are some available funds.

**Comment by Joohansson** [comment]
Yeah sure, it can check for hidden funds, no problem but each check require one API call and the public APIs have rate limiting. 10-20 is ok but there could still be rare cases people have more. I think this would be a nice feature. Could add a warning that there is no guarantee that all accounts are checked or something.

**Comment by Joohansson** [comment]
Actually there is a tool that does this. I wrote it myself a while back. You just enter a seed, private key or mnemonic and it will send all funds to another account. It support any index but max 100 each time. It's using local pow only so a little bit slower than dpow. It will also receive any pending that may be waiting. It even support Ledger passphrase in case anyone need to recover that. 

https://tools.nanos.cc/?tool=sweep

**Comment by Joohansson** [comment]
@mikerow Nault now has a wallet sweeper that can be used on its own seed if you want to empty the wallet
