### ISSUE TITLE
Include rep changes in the account details

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#310]
Nault is a nice block explorer but it's missing rep changes in the table. Probably also Epoch blocks. It's not only the latest rep that is interesting but also how it changed and when. Especially if you use Nault as a block explorer for external accounts. Also good as verification when you change the rep, now it looks like the change didn't make it (if you are expecting it to show in the table). Most people are used to other block explorers.

Not sure how to present it though? What to call the columns. Simply put "Rep Change" in the amount column? Or include the rep it was changed to somehow?
![image](https://user-images.githubusercontent.com/2406720/108163126-c5eb6d80-70ee-11eb-9614-9836905ff2a2.png)

**Comment by keerifox** [comment]
the transactions list has to be redesigned, i'll think how the rep changes can be presented on the list
