### ISSUE TITLE
Change UI colors

### ISSUE THREAD

**Issue by MikeRow** [Nault/Nault#32]
Changing UI colors, maybe in tune with the logo, would make it look better. (not saying it's not good now)

**Comment by Joohansson** [comment]
I will probably push the new logo design tomorrow. Make a suggestion and PR it =)

**Comment by aleksre** [comment]
It could use a light redesign to make it look more modern IMO. New colors, new (and bigger) font and more space in general. Perhaps make it look slightly more like https://nano.org/ ?

**Comment by MikeRow** [comment]
> I will probably push the new logo design tomorrow. Make a suggestion and PR it =)

Let me know if need something with it

**Comment by Joohansson** [comment]
Did some basic redesign of the button colors and shape. More will be needed.
42752341700717091b40414d81c2a69b6559ba82
a4d09eddf49fdba50163ab14c57b91e184808923

**Comment by MikeRow** [comment]
Hey! The new logo looks much better. I may provide some button icons or whatever. Let me know.

**Comment by keerifox** [comment]
i think this can be closed now
