### ISSUE TITLE
Incorrect Balance

### ISSUE THREAD

**Issue by Jordan01010** [Nault/Nault#333]
After receiving a payment when I reopen my wallet it shows my old balance before the transaction I have found using the "force reload" feature pulls through the new balance.

**Comment by keerifox** [comment]
all balances and transactions you see depend entirely on the backend server that is set in the app settings. some may be out of sync at the moment, please try different ones

**Comment by BitDesert** [comment]
Correct, out of sync nodes. A backend switch helps.
