### ISSUE TITLE
Progressive Web App (PWA)

### ISSUE THREAD

**Issue by fallerOfFalls** [Nault/Nault#334]
Perhaps as a progressive web app?

I want to be able to turn my old Android phone into an offline signing device. With all the QR code options for remote signing, a slick experience like the Ellipal hardware wallet would be possible.

In theory we can use an Android device via a web browser, but if the browser crashes or the phone switches off and you have to switch the internet back on to reload nault, the whole purpose of remote signing is defeated.

A simple Android app designed only to be used for offline signing, intended as a companion to Nault would also work. It could even scream at you if it ever detects an internet connection :D

**Comment by keerifox** [comment]
yeah i've been thinking about PWA, should be doable. it's like 2 html lines, one for iOS and one for Android isn't it? (not including the offline mode, just to be able to add it to home screen and launch as a fullscreen app)

```html
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
```

**Comment by Joohansson** [comment]
I like the idea!

**Comment by aleksre** [comment]
PWA was actually implemented already in a separate branch a while back: https://github.com/Nault/Nault/compare/master...aleksre:Progressive-web-app

But didn't finish it because the mobile experience wasn't that good back then. This is much better now though.

**Comment by fallerOfFalls** [comment]
I don't know that much about PWAs. Would it solve my problem (fully functional offline, not forgetting anything after a restart/not needing to connect to the server again)?

**Comment by aleksre** [comment]
Yes. The app itself including images are cached for offline use and even some networks calls too like the current Nano price and rep status.

**Comment by fallerOfFalls** [comment]
I hereby place a bounty on this issue of $300, payable in Nano of course.
(Expires 2021-06-23)

**Comment by aleksre** [comment]
Hehe, point taken 😅

Will create a draft PR so we can get the ball rolling on this.

**Comment by Joohansson** [comment]
@fallerOfFalls It's making progress ^^

**Comment by fallerOfFalls** [comment]
I have a new question/concern about this.

For my use case: an offline mobile device that stays offline indefinitely, will the software stop being compatible with changes to the protocol and particularly, what data is stored in a block? Does the software check that the block is valid before signing? If so, any changes to what a block contains, will cause the signing to fail, since the software on the mobile offline signing device will not be up-to-date.

**Comment by aleksre** [comment]
Mandatory block changes will be very rare and updating the app without exposing your keys is still fairly simple. Just do a factory reset on the device which will delete everything including your keys. It will then be safe to go online and redownload Nault. After that you can return to permanent flight mode before entering your mnemonic into the app.

But again, this should be an extremely rare occurrence.

**Comment by fallerOfFalls** [comment]
@aleksre The [deployed version of the branch](https://nault-git-progressive-web-app-aleksre.vercel.app/) works!

Who gets the bounty?

**Comment by fallerOfFalls** [comment]
Also, I need to lose my open source development etiquette to say that this is SO FREAKING COOL! I've been merrily signing transactions offline all afternoon. I create the block with my computer, then scan it with the offline device which is left in QR code scanning mode, tap sign, then scan the signed block with my phone and submit.

This is in many ways a user experience improvement over Ledger Nano S.

Could be made even slicker by not asking for confirmation when signing receive blocks. I also don't see why it needs to ask before submitting a signed block to the network. But even so, it is extremely cool. Thanks for making this happen.

**Comment by fallerOfFalls** [comment]
Bounty paid to @aleksre. Payment made using the software he made.

**Comment by aleksre** [comment]
Thank you very much! ❤️ 

Let me know if you notice any issues with it.
