### ISSUE TITLE
Nothing happens when checking for updates

### ISSUE THREAD

**Issue by D3V-IN** [Nault/Nault#336]
Hi,
I'm using Nault on desktop 0 1.10.1 and when I click "Help" -> "Check for Updates" nothing happens.

I saw this on the repo "Avoid saving windows state on desktop app close" and thought I would try the update button.

Not sure if it does actually update in the background but you don't see anything or if it isn't updating?

Regards

**Comment by Joohansson** [comment]
That's because 1.10.1 is the latest version. If you try again in 30min, there will a 1.10.2

**Comment by D3V-IN** [comment]
Holy sh*t what a fast response.
Cool, thank you
