### ISSUE TITLE
[Ubuntu] Error: Unable to load Ledger transport: cannot open device with path /dev/hidraw8

### ISSUE THREAD

**Issue by tejashah88** [Nault/Nault#348]
**Describe the bug**
I'm trying to connect Nault with my Ledger Nano X that I just unboxed and set up. I'm running Kubuntu 20.04 LTS and I'm getting the error above. I haven't tried it on Windows yet, and I'd prefer to keep my crypto apps on my Linux partition. Thanks!

**To Reproduce**
1. Go to 'Configure Wallet'
2. Click on 'Use Ledger'
3. Connect the Ledger Nano X and open the Nano app
4. Click on "Connect via USB"
4. See error from DevTools

**Expected behavior**
It's supposed to connect the Ledger wallet to Nault.

**Desktop App (please complete the following information):**
 - OS: Kubuntu 20.04 LTS
 - Version: 1.10.3

**Comment by agilob** [comment]
You haven't installed udev rules from ledger.

**Comment by agilob** [comment]
https://support.ledger.com/hc/en-us/articles/115005165269
