### ISSUE TITLE
DATE column not displayed on mobile

### ISSUE THREAD

**Issue by fallerOfFalls** [Nault/Nault#371]
**Describe the bug**
The date column doesn't appear on mobile (even in desktop mode). This is an issue as the 'sign block' button is in the date column. Might be related to #318 

**To Reproduce**
1. On a mobile phone, go to accounts
2. Click on an account
3. Scroll down to transactions
4. Try to find the DATE field

**Expected behavior**
Should be able to scroll sideways and see the sign block button.

**Screenshots**
<img src="https://i.ibb.co/pXHcmYH/Screenshot-20210502-153430.png" alt="Screenshot-20210502-153430" border="0">

**Smartphone (please complete the following information):**
 - Device: Fairphone 2 and Fairphone 3
 - OS: Android 7.1.2 and Android 10
 - Browser: Chrome, Brave
 - Version: of Nault? I don't know. just the one running on the web currently.

**Comment by keerifox** [comment]
unrelated to #318 and it's already known, will try to fix it when i get time, by adding date/actions underneath amount on small/medium viewport views (when the date column is hidden)
