### ISSUE TITLE
Import Wallet attempts

### ISSUE THREAD

**Issue by NashJames** [Nault/Nault#379]
**Is your feature request related to a problem? Please describe.**
My understanding is that all it takes to import an existing wallet and have access to the Nano is something like the 24 words mnemonic. So if someone wrote a script to try combinations of words, they could eventually brute-force their way into someone's wallet?

**Describe the solution you'd like**
A max login attempts per 24 hours for that IP? You may have a better solution.

Also, an advisory comment about how to make your Nano more secure? Could appear as a warning for anyone with a balance over a certain amount?

**Additional context**
My knowledge of what makes wallets secure and how to make them more secure is still fairly lacking, so I apologise if I've misinterpreted this.

**Comment by shryder** [comment]
It'll take someone a very very long time to crack your seed because of the amount of possible combinations. Say billions of years I think. Applies to like all cryptocoins.

**Comment by Joohansson** [comment]
Yeah putting a rate limit on Nault won't change anything since there are other methods that are million times faster. And billions of years is a huge underestimate, more like billions of years if you fill the whole universe with computers.
