### ISSUE TITLE
Missing back button

### ISSUE THREAD

**Issue by fairking** [Nault/Nault#380]
Missing back button on most of the pages of the app

**Comment by BitDesert** [comment]
Which back button in which type of app? Examples? Screenshots?

**Comment by fairking** [comment]
![image](https://user-images.githubusercontent.com/13495631/118714969-f8eeeb80-b81a-11eb-9d5b-6ca4bf54cb65.png)

This is just an example but it literally everywhere.

**Comment by fairking** [comment]
![image](https://user-images.githubusercontent.com/13495631/118715369-74509d00-b81b-11eb-92ae-dc2b708c5fe3.png)

**Comment by keerifox** [comment]
to navigate to the Accounts page you can use the sidebar navigation

to navigate to the previous page you can use the mouse navigation buttons
