### ISSUE TITLE
"Export Address Book" button unresponsive

### ISSUE THREAD

**Issue by fallerOfFalls** [Nault/Nault#393]
**Describe the bug**
Depending on the contents of the address book, the address book export function will show only:
>Export all address book entries to a file or QR Code/URL.
>
>Note: Exported address book will NOT be encrypted by your wallet password.

followed by the export address book button (which is unresponsive). The QR code and "export as file" buttons are missing.

**To Reproduce**
1. Name an address "€" or add more than about 12 addresses (depends how long the labels are)
2. reload and clear cache
3. Click on import/export
4. click on export address book

**Expected behavior**
There should be a QR code there and:
>Scan the QR code on any device to import your address book!
>
>You can also import your address book by using the URL below. 
>
> COPY TO CLIPBOARD       EXPORT AS FILE

**Web (please complete the following information):**
 - OS: Debian 9
 - Browser Firefox
 - Version 78.10.0esr (64-bit)

**Comment by Joohansson** [comment]
Interesting. The € is causing the base64 encoder to fail
![image](https://user-images.githubusercontent.com/2406720/120438815-1b881500-c382-11eb-9239-e208dfe55b94.png)

The other issue with long or many labels are causing the QR to fail
![image](https://user-images.githubusercontent.com/2406720/120439000-4ecaa400-c382-11eb-9a81-a194ed2a84f5.png)

Will see how to solve this.

Might be a solution for btoa here: https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte

Alt here (most likely better): https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa#unicode_strings

For QR, maybe just check the size and disable the QR for large address books. File export will still be possible
