### ISSUE TITLE
Add RON to the list of available FIAT currencies

### ISSUE THREAD

**Issue by tepesalexandru** [Nault/Nault#395]
I am from Romania and here the local FIAT currency is RON. I would love to see the value of Nano I own in RON.

This feature involves adding RON to the list of FIAT currencies here
![image](https://user-images.githubusercontent.com/22937903/120541469-97ba4100-c3f2-11eb-8000-b87c175048d2.png)

And being able to see the converted amount here
![image](https://user-images.githubusercontent.com/22937903/120541703-e23bbd80-c3f2-11eb-82de-0fd37394b245.png)

**Comment by BitDesert** [comment]
RON isn't supported by the CoinGecko API we use for the market prices, that's why we can't add it.
You could ask the CoinGecko Support if they could add it.

https://www.coingecko.com/api/documentations/v3#/simple/get_simple_supported_vs_currencies
