### ISSUE TITLE
QR Code With Wrong Address

### ISSUE THREAD

**Issue by lopezpagan** [Nault/Nault#398]
**Describe the bug**
When I scan the QR Code with the Binance QR scanner it shows a message with an error in the address format.  When I check the address and it looked like this 'nano:nano_address'.  I removed the 'nano:' from the address and it worked.

**To Reproduce**
1. Go to 'Safepal app'
2. Click on 'Binance'
3. Withdraw NANO and use the scanner to read the QR Code in the NANO Wallet.

I checked with another QR Code Reader and there was the extra 'nano:' word.

**Expected behavior**
Scan the QR Code and fill the input field with the NANO address.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 7
 - OS: Android Latest 
 - Used the Safepal App 
 - Used the All Code Reader

**Comment by keerifox** [comment]
Nault is using the Nano standards for QR and URI: https://docs.nano.org/integration-guides/the-basics/#uri-and-qr-code-standards

This is an issue with Safepal App rather than Nault
