### ISSUE TITLE
Missing alert when changing Wallet Storage option

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#428]
![image](https://user-images.githubusercontent.com/29272208/126132049-5f591f18-b46b-42a3-9f2a-2d1941ca9f6d.png)

changing wallet storage option to None should display this alert, word in word except the first line which should say
"You are about to disable storage of any wallet data, which means **there will be no wallet configured next time you use Nault**"

![image](https://user-images.githubusercontent.com/29272208/126132823-5dc849e1-1623-46ca-b3f0-ac005216156e.png)

pressing Cancel could change the option back to its previous value, pressing OK could force save the wallet storage option (so there is no more need to save the options manually for that specific setting)

![image](https://user-images.githubusercontent.com/29272208/126133543-13a0ac13-1181-424b-b8cb-1107ef2827b6.png)
e.g. pressing this shouldn't save Wallet Storage option since that should be done via dialogue only

**Comment by Joohansson** [comment]
@keerifox When will the dialog show? Directly when changing the option or when pressing "update wallet settings"? We have a similar warning when changing PoW multiplier but only after pressing save. If we save directly when changing the option it can be a bit confusing if other option changes have been made as well. Should they be saved or not.

![image](https://user-images.githubusercontent.com/2406720/126597875-c610dbcd-943b-418b-89c4-fcba7cf0460e.png)

**Comment by keerifox** [comment]
either option is fine by me, if "saved" / "unsaved" state is unclear, could replace the buttons with an inactive buttons like this

![image](https://user-images.githubusercontent.com/29272208/126666045-6addd09d-5c51-40e5-8dc9-b5a7f25cb002.png)

(placeholder button text, can't think of anything better)
