### ISSUE TITLE
Incorrectly styled buttons on some layouts

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#437]
good example (small viewport):

![image](https://user-images.githubusercontent.com/29272208/126669924-9e0d9210-b647-41e3-8b7d-fb8254a4ba5e.png)

good example (large viewport):

![image](https://user-images.githubusercontent.com/29272208/126669978-dcafdb02-bfef-45a7-ba69-aeacb67edc42.png)

(must be right-aligned)

code for those can be found in send.component.html around line 100

\-

bad examples:

1. address book new entry

![image](https://user-images.githubusercontent.com/29272208/126669510-58d1c652-2433-4c31-a5fe-ed130de4128a.png)

2. rep book new entry

![image](https://user-images.githubusercontent.com/29272208/126669648-dae0320e-6de6-47c4-8f30-347976453866.png)

3. address book import confirmation

![image](https://user-images.githubusercontent.com/29272208/126669798-cee9a912-fbdd-4225-b5c9-5fcce00f3b5b.png)

4. representatives page

![image](https://user-images.githubusercontent.com/29272208/126677812-6a15e582-9382-404e-aaf5-9c695f50aa9d.png)

5. sign/process block

![image](https://user-images.githubusercontent.com/29272208/126906654-90d92878-4c7b-4734-8c71-47816d49f42b.png)

**Comment by andrew-m-higgs** [comment]
What is wrong with 5? Is it because on a larger screen they should be aligned right and the size they need to be rather than the size of the boxes above them? Looks quite neat to me.

**Comment by keerifox** [comment]
reopening this due to regression removing vertical spacing

![image](https://user-images.githubusercontent.com/29272208/167292651-ba08d3a3-a039-46ac-8b85-a72e22532435.png)
