### ISSUE TITLE
Deep link button or not?

### ISSUE THREAD

**Issue by Joohansson** [Nault/Nault#46]
I added this button for deep link support (on the receive screen). That usually works to open an account in another wallet but I don't think it's working for Nault since Nault wants to open itself since it's a wallet. Does it make any sense at all to have it? Or should I remove it again? @BitDesert 

![image](https://user-images.githubusercontent.com/2406720/86920783-8907d300-c12a-11ea-81c8-5e57d61dda3d.png)

**Comment by BitDesert** [comment]
I would remove it as Nault is already you wallet, so it does not make sense to open it in another wallet again.
The QR code would be used to show it directly to other people.
If we could implement a Share dialog like https://web.dev/web-share/ that would open e.g. WhatsApp with the QR and address that would be cool.
