### ISSUE TITLE
Display the Representative account even if it's "Unknown"

### ISSUE THREAD

**Issue by tombertrand** [Nault/Nault#461]
**Is your feature request related to a problem? Please describe.**
When looking at the sidebar, I can see that my account is using an "Unknown Representative" but I'd still want to be able to know which is its address

![image](https://user-images.githubusercontent.com/19352322/127575033-5b96df35-2cb8-41aa-a3e5-263fd37456af.png)

**Describe the solution you'd like**
Add the rep's `nano_` address somewhere in the formation bubble

**Comment by keerifox** [comment]
You can view the addresses of your representatives in the account details:

![image](https://user-images.githubusercontent.com/29272208/130827189-6b9ebd13-a7d3-4a12-993a-7b3dfcb53241.png)

or under Settings -> Representatives

![image](https://user-images.githubusercontent.com/29272208/130827289-7a3dcde2-38ed-400a-9fa3-e59d37739638.png)

\-

@BitDesert this used to say "Unknown Rep 0.00%" and "Unknown Rep represents you..." before transloco, which was clearer / easier to read

**Comment by andrew-m-higgs** [comment]
Does anyone still need this or does Keerifox's response (which I think is a better 'solution') suffice for your needs?
At a push something like this could be done...
![image](https://user-images.githubusercontent.com/404121/134047538-36e8850a-2837-4771-b9dc-f31dc694342a.png)
...however, I don't see it as being particularly useful. The full address does not fit into the space available in the bubble.

**Comment by tombertrand** [comment]
My issue was when an account was created with code and not from a wallet iirc, my Representative was set to myself and it didn't show in the account details.

**Comment by andrew-m-higgs** [comment]
Ahh. So perhaps instead of 'Unknown' it should warn that you represent your 'Self'.
