### ISSUE TITLE
Translations and address book labels

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#463]
**Describe the bug**
You can rename an account to "Konto #5"

**Expected behavior**
You should not be able to rename an account to "Konto #5" (regardless of which language is used)

**Additional context**
https://github.com/Nault/Nault/blob/bbb79ca600d67b774332c6cd43b7d534e89e214e/src/app/components/account-details/account-details.component.ts#L554
https://github.com/Nault/Nault/blob/bbb79ca600d67b774332c6cd43b7d534e89e214e/src/app/components/address-book/address-book.component.ts#L277

**Comment by andrew-m-higgs** [comment]
By this do you mean that if I have language set to German I should not be able to set to 'Konto #5'. If language is set to English then not allowed to set to 'Account #5'.

Or do you mean that regardless of language 'Konto #5' and 'Account #5' should not be allowed?
