### ISSUE TITLE
Improve "Add Account" error message when Ledger device is disconnected

### ISSUE THREAD

**Issue by clemahieu** [Nault/Nault#475]
When pushing "Add New Account" when the ledger is in a disconnected state it displays an error message "Unable to add new account: Cannot read property 'setExchangeTimeout' of null.

It seems to be dereferencing a null value when calling 'this.ledger.transport.setExchangeTimeout'

A more specific error message would be helpful leading the user to reconnect the ledger connection.

**Comment by andrew-m-higgs** [comment]
Hi there

I have made a pull request for a potential solution to this. In the createAccount() function I added a check for isLedgerAccount and LedgerStatus !== READY. bcdbf5e
