### ISSUE TITLE
Inaccurate description when no wallet is configured

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#486]
when changing Wallet Storage to None:

![image](https://user-images.githubusercontent.com/29272208/135838645-07c86d08-6274-4ade-ac57-247f3ef812ec.png)

perhaps we could hide last 2 lines and only show this WHEN NO WALLET IS CONFIGURED:

![image](https://user-images.githubusercontent.com/29272208/135838976-4ea7447f-199d-4efa-ab5a-031ca6fe49b2.png)

**Comment by BitDesert** [comment]
I've seen this popup message in different places in the app, I think even with slightly different strings.
We should write a general message which works in every occasion where the wallet is deleted.

**Comment by keerifox** [comment]
> We should write a general message which works in every occasion where the wallet is deleted.

last two paragraphs (paragraph 2 and 3) are already the same across deleting wallet data / creating new wallet, the paragraph 1 changes based on context of the action you're performing, which should stay as is
