### ISSUE TITLE
Can't install dependencies. Missing `usb`

### ISSUE THREAD

**Issue by igorcafe** [Nault/Nault#495]
**Describe the bug**
When trying to install the project dependencies with `npm i`, I get:
```js
npm ERR! code 1
npm ERR! path /home/igor/Git/Nault/node_modules/usb
npm ERR! command failed
...
```

**To Reproduce**
It might be related to the version I am using (see below), since the project uses node 14.x and npm 6.x.
1. Clone the repo
2. `npm i -g @angular/cli`
3. Enter `Nault/` folder
4. `npm i`
5. See error

**Quick solution**
```
npm i usb
npm i
```

**Better solution**
Add usb to package.json?

**System and Node info:**
 - OS: Manjaro 21.1.6
 - Node: v16.11.0
 - Npm: 7.24.0

**Comment by BitDesert** [comment]
We need to install some OS dependencies when we compile our desktop builds, maybe those are missing as well? https://github.com/Nault/Nault/blob/master/.github/workflows/ghpages.yml#L25-L26

**Comment by igorcafe** [comment]
You are asking if these dependencies are missing in my system?
I can't find the right packages for Arch-based, but I don't think so, since it worked installing `usb`.

**Comment by BitDesert** [comment]
Do you get the same error when using NodeJS 14? Currently we use that version in our build pipeline.

**Comment by igorcafe** [comment]
You are right.
With version 14 apparently works fine. 
I believe I was trying with Node 16.
