### ISSUE TITLE
Use XNO, Ӿ, nano

### ISSUE THREAD

**Issue by BitDesert** [Nault/Nault#496]
**Is your feature request related to a problem? Please describe.**
The NF switched to the XNO ticker and introduced the new currency symbol Ӿ:

https://medium.com/@nanocurrency/say-hello-to-xno-7ed55e419e3f

https://xno.nano.org/

**Describe the solution you'd like**
All occurrences in the wallet should use the alternative symbol Ӿ or the proposed (but not yet included in Unicode) symbol with the double strokes.

**Comment by keerifox** [comment]
i'm waiting on #476 before working on this

planning to use svg with double strokes
