### ISSUE TITLE
Hover notification for 0 balance wallets that contains raw.

### ISSUE THREAD

**Issue by gigaion** [Nault/Nault#505]
**Is your feature request related to a problem? Please describe.**
When viewing account balances, the wallet will display a 0 balance even when it contains raw.

**Describe the solution you'd like**
Solution is to add a [i] hover image next to the 0 XNO balance. When you hover or click on this image, it will show a tooltip with the amount of raw the account has.

This will also enable you to determine at a quick glance which balances are truly zero (if they lack the hover image).

**Comment by keerifox** [comment]
i considered using a sign so the balance appears something like "~0", but currently the minimum displayed amount is worth 0.00000384 usd so i don't think it's that important to show in the UI

**Comment by gigaion** [comment]
Yes your suggestion of adding "~0" is still an improvement.
If you have a dozen wallets, you don't want to have to search through each wallet to find the non-empty one.

Preferably a way to see the raw balance when hovering the mouse would be useful.

**Comment by keerifox** [comment]
> Preferably a way to see the raw balance when hovering the mouse would be useful.

you should be able to hover on the balance amount to see raw amount that isn't shown
