### ISSUE TITLE
Hot to import an existing account?

### ISSUE THREAD

**Issue by fairking** [Nault/Nault#513]
I cannot import existing account. Clicking the link Add new account simple adds a new fresh one without even asking any questions.

I don't understand this UI guys.

![image](https://user-images.githubusercontent.com/13495631/148658194-aadbfe53-08ee-4607-ab4c-3e074edf8ea0.png)

**Comment by keerifox** [comment]
Secret recovery seed + certain account number will always give you the same address

If you had funds in Account #5 before, you can either:

a) press "add new account" until you see Account #5
b) use advanced mode, enter "5" at the top and click the "add new account" button

**Comment by fairking** [comment]
Sorry, I don't understand what you just said. I have a seed of the account. I managed to find Settings -> Configure New Wallet. But when I enter the seed it does not add any account. Also one of my existing accounts disappeared after I tried to import.

**Comment by keerifox** [comment]
you can only use 1 secret recovery seed at the same time

to see accounts of the wallet, you can press "add new account" button

**Comment by fairking** [comment]
> you can only use 1 secret recovery seed at the same time

So you are saying one seed represents many accounts? how is it possible? Ok. Simple example. If I put the seed to the Natrium, what will it get me?

> to see accounts of the wallet, you can press "add new account" button

The meaning of "Add new account" for me is to generate a new wallet. Does it do something completely different?

All of that is very confusing. I cannon get the point of those accounts from now.

**Comment by BitDesert** [comment]
1 seed = up to 2^11 accounts
"Add new account" just add a new account inside of your wallet. Natrium has the same terms for accounts + wallets.

For more information go to https://medium.com/nano-education/nano-how-1-seeds-keys-1b067fdee6fc

**Comment by fairking** [comment]
Thank you for the explanation.
