### ISSUE TITLE
No send button

### ISSUE THREAD

**Issue by fairking** [Nault/Nault#514]
I am in account details. Why there are no "Send" button?

Instead I should go to Send menu, and then choose the account. It is very inconvenient.

**Comment by keerifox** [comment]
there is one if you are on a portable device and/or using a narrow window, otherwise select the account in sidebar and just navigate to the Send Nano page where it will already be pre-selected

**Comment by fairking** [comment]
Thanks. Would be nice to have extra button here:

![image](https://user-images.githubusercontent.com/13495631/148679477-913db0e9-2759-4337-8ca7-5db8a982a77e.png)
