### ISSUE TITLE
Remove warning when replacing a Ledger wallet

### ISSUE THREAD

**Issue by aleksre** [Nault/Nault#516]
Whenever the currently configured wallet is a Ledger device and the user tries to configure a new wallet, the following warning is displayed:

![image](https://user-images.githubusercontent.com/1097444/149826408-b60ef723-da2d-4c54-8af6-535d1868e533.png)

This is displayed regardless of what the new wallet is. It could be the same Ledger device, a different Ledger device, a new hot wallet, or an existing hot wallet.

This big red warning sends a strong message to the user that they should think closely about what they are about to do. A warning like this should not be overused as it might desensitize the user to warnings. Such a warning is justified when the user tries to replace a seed/private key based wallet of which they may not have a backup, but IMO *not* justified when replacing a Ledger based wallet for the following reasons:

- Since the current wallet is a Ledger device, we know that the user has both access to their Ledger and the PIN-code. This means replacing the wallet is a completely harmless operation that they shouldn't be "warned" against. They can simply reconnect it at any time. Even if the user has since lost access to the device or the PIN, stopping them from configuring a different wallet, will not help at all. The Ledger wallet cannot be used until it is reconnected.
- Informing the user about the importance of their Ledger seed/mnemonic probably creates more confusion than it clarifies. It is completely impossible to complete the Ledger setup process without writing down your mnemonic, and ensuring that the user understands its importance is fully on Ledger, not Nault. Without a seed backup, all crypto on the Ledger is at risk of being lost, not just the Nano wallet. Some users might think there is something specific about Nault they need to write down and make a copy of, while in reality they already did everything right. Even if they somehow destroyed their backup, stopping them from configuring a new wallet will not help.
- In many cases the user might be trying to connect the very same Ledger device that Nault remembered from last time. Seeing this warning then, is particularly odd.

I therefore suggest we remove this warning.

**Comment by keerifox** [comment]
i suggest we at least keep the following message on a blue-colored info alert

![image](https://user-images.githubusercontent.com/29272208/149839386-5f98ad3c-813c-4b15-92a4-c304fc4d0af6.png)

the reason is.. user might not realise they are no longer using ledger

\-

> It is completely impossible to complete the Ledger setup process without writing down your mnemonic, and ensuring that the user understands its importance is fully on Ledger, not Nault.

i don't mind removing that part very much, but it has never hurt anyone to guide users about something they might have forgotten or never properly understood. i've met A LOT of people in both of these categories

**Comment by aleksre** [comment]
> i suggest we at least keep the following message on a blue-colored info alert

Yeah that's fine.

> i don't mind removing that part very much, but it has never hurt anyone to guide users about something they might have forgotten or never properly understood. i've met A LOT of people in both of these categories

Speaking generally, there is definitely such a thing as too many warnings and too much text. Excessive warnings decrease impact of each, and the more text there is the less users will read. We should try to keep non-essential text to a minimum and employ "show, don't tell" when possible.
