### ISSUE TITLE
To account address is not valid

### ISSUE THREAD

**Issue by ABOUSETTA89** [Nault/Nault#581]
Hello,
I'm trying to send nano from Nault, when I specify the recieving address I get an error saying it's not valid, I tried with multiple adresses and I get the same issue.
My account is linked to ledger nano S.

Can you please help ?

**Comment by keerifox** [comment]
the post on reddit with similar contents has been deleted by its author. have you resolved the issue?

**Comment by ABOUSETTA89** [comment]
Hello,

Yes I have resolved it.
Thank you !

Kind regards,
