### ISSUE TITLE
Desktop version fails to build ('openssl_fips' is not defined)

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#584]
the error occurs while trying to build `abandonware/bluetooth-hci-socket@0.5.3-8` from source:

`npm ERR! gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp`

relevant node-gyp issue thread:
https://github.com/nodejs/node-gyp/issues/2673

dependency tree:
```shell
npm ls @abandonware/bluetooth-hci-socket@0.5.3-8
nault@1.18.0
`-- @ledgerhq/hw-transport-node-ble@6.27.1
  `-- @abandonware/noble@1.9.2-15
    `-- @abandonware/bluetooth-hci-socket@0.5.3-8
```

**Comment by nanogarden** [comment]
When manually going through these steps, this error appears when running the following command:

`npm run desktop:local`

Appending the flag to that specific command fixes the issue:

`npm run desktop:local --openssl_fips=''`

**Comment by nanogarden** [comment]
After some testing building in my computer (OS: ArchLinux, npm version: 8.19.4, node version: 16.20.1), my recommendation that would allow for an easy installation is to modify the `desktop:build` and `desktop:local` scripts directly in the packages.json file. 

Each one of these should include an openssl configuration flag.

These work:

`"desktop:build": "NODE_OPTIONS=--openssl-legacy-provider npm run wallet:build-desktop && npm run desktop:compile",`

`"desktop:local": "npm_config_openssl_fips='' electron-builder -p never"`

With this modification, the github build release should also work.

From looking at the above-cited issue (https://github.com/nodejs/node-gyp/issues/2673#issuecomment-1477682343), these flags may not be necessary with more recent versions of electron and electron-builder, so it may be a worthy project to update the dependencies.

**Comment by nanogarden** [comment]
You can see the successful action run here, modifying only the packages.json file: https://github.com/nanogarden/Nault/actions/runs/5843583237

The "cross-env" npm package allows you to pass a variable in a way that will be accepted across platforms. So, the flag is passed in this way:

`"desktop:local": "cross-env npm_config_openssl_fips='' electron-builder -p never"`

And cross-env is added to the dependencies as:

`"cross-env": "^7.0.3",`

**Comment by nanogarden** [comment]
Hey @keerifox, I know this is taken care of, but I noticed while looking at the PR's that PR #566 "Bump electron from 9.4.4 to 18.3.7" built correctly, while several builds before it and everything after it failed to build. 

So, I have tested by removing the openssl_fip flag and updating the electron version to the version that the bot jumped to (^18.3.7), and it builds: https://github.com/nanogarden/Nault/actions/runs/5859447706


I'm just letting you know in case that you consider a cleaner solution than passing a flag!

I also tried bumping electron to the newest version (25.5.0), but that fails: https://github.com/nanogarden/Nault/actions/runs/5859529104/job/15885732316
