### ISSUE TITLE
No release files on gihub for 1.18.3

### ISSUE THREAD

**Issue by Mart-Bogdan** [Nault/Nault#608]
There are only tag `1.18.3` but latest release with downloadable artefacts is `1.18.2`

![image](https://github.com/Nault/Nault/assets/775038/ab45914e-6dc5-4c19-95a1-7e5107fed897)

![image](https://github.com/Nault/Nault/assets/775038/823b48af-e25e-47c1-80ea-95f14fa72a7f)

**Comment by keerifox** [comment]
this is due to the desktop version of 1.18.3 not properly functioning despite passing existing unit tests

see #604
