### ISSUE TITLE
Default representatives list needs to be updated

### ISSUE THREAD

**Issue by keerifox** [Nault/Nault#631]
https://github.com/Nault/Nault/blob/c9ed1cca08833e406f9ceb58973e3198d5d66f81/src/app/services/nano-block.service.ts#L15-L23

to remove:
\- My Nano Ninja (shut down)
\- PowerNode (shut down)

unknown:
\- Nanolooker.com (currently offline)

code comments to update:
\- NanoTicker (owned by Ricki instead of Json)

to add:
up to you, but ideally there should be at least ~10 representatives in the list, to avoid centralizing the voting weight from newly created accounts

**Comment by kopeboy** [comment]
I would add nodes hosted by known, long-standing contributors, like:
- gr0vity: `nano_3msc38fyn67pgio16dj586pdrceahtn75qgnx7fy19wscixrc8dbb3abhbw6`
- Patrick: `nano_3patrick68y5btibaujyu7zokw7ctu4onikarddphra6qt688xzrszcg4yuo`
- Gustav (rsnano.com): `nano_1tk8h3yzkibbsti8upkfa69wqafz6mzfzgu8bu5edaay9k7hidqdunpr4tb6`

**Comment by qwahzi** [comment]
A few other long-term community representatives:

- Nanick: `nano_3ekb6tp8ixtkibimyygepgkwckzhds9basxd5zfue4efjnxaan77gsnanick`
- Flying Amigos: `nano_1xckpezrhg56nuokqh6t1stjca67h37jmrp9qnejjkfgimx1msm9ehuaieuq`
- Humble Nano: `nano_3n7ky76t4g57o9skjawm8pprooz1bminkbeegsyt694xn6d31c6s744fjzzz`
- WeNano: `nano_1wenanoqm7xbypou7x3nue1isaeddamjdnc3z99tekjbfezdbq8fmb659o7t`
- NanoCharts: `nano_3chartsi6ja8ay1qq9xg3xegqnbg1qx76nouw6jedyb8wx3r4wu94rxap7hg`
