### ISSUE TITLE
Update Angular Version

### ISSUE THREAD

**Issue by BitDesert** [Nault/Nault#9]
The used Angular version is 5 and is not supported anymore.
It would be better to update it to a more recent version.
The process could break features!

**Comment by NiFNi** [comment]
I started working on something similar like Nault simultanously before Nault was announced. I started with updating all the libs. I haven't tested a lot after updating a lot but it seemed to be running with Angular 9. 
I will probably have a closer look at it again this week. If I can merge it all together and it works without further hiccups I will probably create a PR later this week about this issue.

**Comment by BitDesert** [comment]
I got it working after some issues when updating from 5-->6-->7.
If you could get a look at #21 that would be great! @NiFNi
